// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd71khy80ZuOzbd98tW1Qog8CRGaqXqe8',
    appId: '1:343569930290:web:692d7b9fac26d9ab35842b',
    messagingSenderId: '343569930290',
    projectId: 'fluttertypescript-46cc5',
    authDomain: 'fluttertypescript-46cc5.firebaseapp.com',
    storageBucket: 'fluttertypescript-46cc5.appspot.com',
    measurementId: 'G-Z9H176WJFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtJoPf4W4HOteP7E1dQfeSV0owKZ-fP3U',
    appId: '1:343569930290:android:432914f749065b0335842b',
    messagingSenderId: '343569930290',
    projectId: 'fluttertypescript-46cc5',
    storageBucket: 'fluttertypescript-46cc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdxFs_vizqVaNo0SqLPNhwrYWU5Uy6R50',
    appId: '1:343569930290:ios:241934160cc1b0c935842b',
    messagingSenderId: '343569930290',
    projectId: 'fluttertypescript-46cc5',
    storageBucket: 'fluttertypescript-46cc5.appspot.com',
    iosBundleId: 'com.example.flutterTweetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdxFs_vizqVaNo0SqLPNhwrYWU5Uy6R50',
    appId: '1:343569930290:ios:241934160cc1b0c935842b',
    messagingSenderId: '343569930290',
    projectId: 'fluttertypescript-46cc5',
    storageBucket: 'fluttertypescript-46cc5.appspot.com',
    iosBundleId: 'com.example.flutterTweetApp',
  );
}
